theme: jekyll-theme-cayman
title:            Stephen Pelkofer
description:      'Personal Website, Blog, and Portfolio'

author:
  name      : "Stephen Pelkofer"
  location  : "Madison, WI"
  twitter   : "spelk24"
  email     : "spelkofer24@yahoo.com"
  linkedin  : "spelkofer"
  github    : "spelk24"
  
